### ISSUE TITLE
Website not working properly

### ISSUE THREAD

**Issue by nikhilbyte** [mlcontests/mlcontests.github.io#130]
<img width="1440" alt="Screenshot 2022-12-03 at 3 14 55 AM" src="https://user-images.githubusercontent.com/62005061/205395458-68240dc4-ecd8-4c91-9649-eb36a0b69168.png">

**Comment by hcarlens** [comment]
Hey @nikhilbyte, thanks so much for sharing! I can't quite figure out what's going on here, it's looking fine for me (see screenshot below). I'm not on OSX though. Could you press F12 and let me know if you see any errors in the console? 

![image](https://user-images.githubusercontent.com/7941504/205433850-dec2308a-7d04-4eb8-ab4a-8d767133dbf6.png)

**Comment by hcarlens** [comment]
Hi @nikhilbyte, I think this issue is now resolved. Could you let me know if it works for you?

**Comment by nikhilbyte** [comment]
Hi @hcarlens , the website is working without issues at the moment for me
