### ISSUE TITLE
List not visible on mlcontests.com

### ISSUE THREAD

**Issue by hnhparitosh** [mlcontests/mlcontests.github.io#131]
The website is loaded but the list is not visible on the website.
Checked the same on multiple browsers and devices.
![image](https://user-images.githubusercontent.com/36197416/206426626-a214bda7-e473-4e1d-88cd-bf7965430bf0.png)

**Comment by hcarlens** [comment]
Thanks so much for reporting this, looks like this is the same thing mentioned in https://github.com/mlcontests/mlcontests.github.io/issues/130 which I closed prematurely. 

It's weird, I'm not able to replicate it. Would you be able to show me the contents of your console (F12) as well as the network tab? Then I'll try to fix this ASAP!

![image](https://user-images.githubusercontent.com/7941504/206427943-ba1d2dbe-4238-422a-b9ff-dc166db9858d.png)
![image](https://user-images.githubusercontent.com/7941504/206428001-6e40a715-e906-4bc5-9281-39ec469f49b2.png)

**Comment by hnhparitosh** [comment]
I guess it fails to fetch the competitions.json
![image](https://user-images.githubusercontent.com/36197416/206440183-a646d127-af58-4a52-adc5-c49c21f79ad3.png)

**Comment by hcarlens** [comment]
Thanks! I'll try to fix this in the next few days.

**Comment by hcarlens** [comment]
Hi @hnhparitosh, I've implemented something which I think should fix this issue. Could you let me know if it works for you?

**Comment by hnhparitosh** [comment]
Hello, the website seems fine, the list is being properly displayed 👍

**Comment by hcarlens** [comment]
Thanks for confirming, and thanks again for the debug info!
