### ISSUE TITLE
Gather more competitions

### ISSUE THREAD

**Issue by Tenich** [mlcontests/mlcontests.github.io#20]
There are some similar sites (e.g. challenges.ai) which have much more running competitions available. 

I think mlcontests could benefit from auto crawling some popular competition platforms (maybe with hand post-filtering)

**Comment by hcarlens** [comment]
Good point. One category of competitions we're missing entirely is competitions without prizes (e.g. conference competitions). 

As for auto-crawling - this would be great, but currently there's no real backend to mlcontests, so it would be a big step. Do you have a suggested way of doing it?
