### ISSUE TITLE
Adding a new compeititon

### ISSUE THREAD

**Issue by jsuarezv** [mlcontests/mlcontests.github.io#25]
Hello,
This is José Suárez-Varela, from Barcelona Neural Networking center-UPC. I would like to request you to add the competition we have started recently. This is the first competition in the world on Graph Neural Networks applied to computer networks:

Name: Graph Neural Networking challenge 2020,
Website: https://bnn.upc.edu/challenge2020,
Type: Supervised Learning - Graph Neural Networks,
Deadline: 10 Sep 2020,
Platform: BNN platform,
Prize: Certificates and presentation at international conference organized by ITU and sponsored by Cisco
Sponsor: ITU/Cisco

Thank you,
José

**Comment by hcarlens** [comment]
Hi José,

Thanks for reaching out! I've added the competition: https://github.com/mlcontests/mlcontests.github.io/commit/48d6aeb299ec734a71391ee86a36f0e34f659ea7

Unfortunately we can't currently put non-monetary prizes in the prize column as that breaks the sorting! But it's something I'm planning on working on. For now I've put the prize as $0 and people can see the actual prize when they click through.
