### ISSUE TITLE
View old competitions

### ISSUE THREAD

**Issue by jonatanvm** [mlcontests/mlcontests.github.io#30]
Same functionality but for old competitions as well.

**Comment by hcarlens** [comment]
Hey! So you'd like to be able to view competitions which have already closed?

I have thought about adding a second page for this, maybe alongside some extra data for those competitions - e.g. who won/what kind of techniques were used by the winners. What do you think about this? Anything else you'd like to see?

**Comment by hcarlens** [comment]
Closing this for now since I won't add it right away.
