### ISSUE TITLE
New contests

### ISSUE THREAD

**Issue by microprediction** [mlcontests/mlcontests.github.io#36]
https://www.microprediction.com/competitions/crypto
https://www.microprediction.com/competitions/electricity

**Comment by hcarlens** [comment]
Thanks @microprediction. Am I right in thinking that these are basically time series/supervised learning problems? Do you provide historical data?

**Comment by microprediction** [comment]
Live time series tasks, yes, where distributional estimates are provided frequently, over http.

**Comment by hcarlens** [comment]
Hi - sorry it's taken me a long time to get back to this. 

I want to add your competitions but I'm really struggling to see what they're actually about. For example, [this one](https://www.microprediction.com/competitions/electricity) says it's about 'electricity prediction'. Does that mean predicting electricity usage in a specific place, or across a grid, or something else? With all the other platforms it's generally really easy to see sample features and labels, but I spent a few minutes looking and couldn't find anything like that on your site. 

If you give me a brief description of a few words for each of the competitions similar to the ones already on [mlcontests](https://mlcontests.com/) then I can look at adding them. 

Alternatively, feel free to create a pull request with all the details (see [this one](https://github.com/mlcontests/mlcontests.github.io/pull/41) for an example) then I can merge it in right away.

**Comment by microprediction** [comment]
Sure I'll do that, but I understand if this is not in scope as microprediction tries breaks the mold. It's really halfway between an ml contest and a market. The contest is live so finding data is actually part of the contest. There's a longer discussion in this [post](https://www.linkedin.com/pulse/dorothy-youre-kaggle-anymore-peter-cotton-phd/) about +/-. Do you want MP i the list still? No offense is taken if not, as I'm sympathetic to the need to limit scope.

**Comment by hcarlens** [comment]
Thanks! Yeah having looked a bit more I think I'm going to hold off adding it here for now as I don't think it will be what most users are looking for. 

Really interesting though, I'll definitely keep an eye on what you're doing. 

Feel free to re-open this issue if you ever end up changing it to be more accessible to people used to Kaggle-style competitions.
