### ISSUE TITLE
DPhi ML Challenges

### ISSUE THREAD

**Issue by chanukyapatnaik** [mlcontests/mlcontests.github.io#40]
Hi Team, 

We at DPhi are a global community of Data Scientists, started with a vision to build Data Culture and Democratize Data Science Learning. We regularly conduct ML/DL education challenges. Could you please list down so that mlcontests community can benefit from it. Our recent edition of Data Sprint is listed here: https://dphi.tech/practice/challenge/58
Let us know if you may need any other information. Many thanks!

**Comment by hcarlens** [comment]
Hi @chanukyapatnaik! Do your challenges have any prize money? Generally we're only listing competitions with prize money on mlcontests at the moment. If they do, feel free to submit a pull request to add your competition (just add it to the bottom of [data.json](https://github.com/mlcontests/mlcontests.github.io/blob/master/js/data.json), and when I merge it will show up on the website).

**Comment by hcarlens** [comment]
Hi @chanukyapatnaik - any update on this? If not I'll close this issue.

**Comment by hcarlens** [comment]
Closing; feel free to re-open in future if things change
