### ISSUE TITLE
Type of contest

### ISSUE THREAD

**Issue by Therzidij** [mlcontests/mlcontests.github.io#7]
I think it would be better to add "Type of contest" as separate column on the front page.

**Comment by hcarlens** [comment]
Thanks! At the moment it shows up as a separate column if your screen is wide enough, but if it's too narrow it collapses. On a narrow screen, would you rather see `type` than `platform`? 

If you want to have a go at changing stuff, the code for that is here: https://github.com/mlcontests/mlcontests.github.io/blob/master/css/style.css

**Comment by Therzidij** [comment]
For me, personally, type is more important than prize or platform.

**Comment by Therzidij** [comment]
Wow, I have found the solution for my case: **Ctrl -**. :-)

**Comment by merrcury** [comment]
I have tested on Narrow Screens like of iPhone 4 & SE & Even Some Feature Phones, I am witnessing "Type" after the "Title" of the challenge. I guess this issue should be closed. 
:iphone: iPhone 4 Screenshot Below:
![mlcontests com_(iPhone 4)](https://user-images.githubusercontent.com/35988194/72137405-c88a7800-33b0-11ea-82bb-0870cd76078f.png)

**Comment by hcarlens** [comment]
@Therzidij @merrcury @Tenich what do you think of the new mobile/responsive layout?

**Comment by merrcury** [comment]
Better than ever.
