### ISSUE TITLE
Cloud provider GPU.LAND seems to be out of operations

### ISSUE THREAD

**Issue by tamirse** [mlcontests/mlcontests.github.io#72]
The cloud provider `GPU.LAND` seems to be out of operations, their website is offline for a while now.

**Comment by fadenb** [comment]
I can not go into details (due to confidentiality) but I can confirm that they are out since around May.

**Comment by hcarlens** [comment]
Weird. Thanks @tamirse and @fadenb, I'll remove them.

**Comment by hcarlens** [comment]
Removed. I've also removed Floydhub, didn't realise they'd shut down: https://blog.floydhub.com/floydhub-has-shut-down/
