### ISSUE TITLE
Feature Request: Date Launched Column

### ISSUE THREAD

**Issue by darien-schettler** [mlcontests/mlcontests.github.io#93]
Hi there, I think this should be relatively straightforward. If you are willing to do the front end that is required for this, I will contribute an updated json file that will have an additional category for all active competitions.

NOTE: I think date launched is quite important as I really enjoy starting a competition along with every else... but I don't like coming in late. Knowing when the competition ends is somewhat indicative of this... but doesn't communicate the whole picture.

Let me know if this makes sense and you're willing to do it and I'll help how I can!

**Comment by hcarlens** [comment]
Thanks for the suggestion @darien-schettler! This is a good idea and I agree with your opinion on people not wanting to come in late. 

I think we'll do this, but give me a few days to think it over first. There are a few other fields that might make sense to add (e.g. conference affiliation, as per https://github.com/mlcontests/mlcontests.github.io/issues/54). Also if there are any others you can think of then let me know.

Btw if you want to get notified about competitions closer to when they start, our [Discord](https://discord.com/invite/nM482gc9h8) (#new-competitions channel) can do that!

**Comment by hcarlens** [comment]
Ok, we'll go ahead with this. If you add the date launched to the json file as a new property called "launched", then I'll do the front-end work to show it afterwards. If you feel like adding another column with "conference" (e.g. "NeurIPS" for some, or "-" for most) to the ones you're editing then that would be appreciated too!

**Comment by darien-schettler** [comment]
Sounds good. I'll take this up ASAP. Thanks!

**Comment by hcarlens** [comment]
Hi @darien-schettler just checking in to see if you're still planning to do this.

**Comment by hcarlens** [comment]
I've added conference affiliation and launched dates to the front-end now! A few things remaining:

- [ ] Make it show up on mobile/card view (currently desktop/table view only)
- [ ] Populate the "launched" data for currently live competitions
![image](https://user-images.githubusercontent.com/7941504/184882252-3c3e22a3-ec16-4df1-bb01-10168d23172f.png)

@darien-schettler are you up for adding some data?

**Comment by hcarlens** [comment]
Closing this since it's now populated for the majority of competitions (and all new ones). I'll add it to the mobile/card view when I make some other changes to that further down the line.
